package route

import (
	"reflect"
	"testing"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestFormatProtocVersion(t *testing.T) {
	tests := []struct {
		name string
		v    *pluginpb.Version
		want string
	}{
		{"nil", nil, "(unknown)"},
		{"no suffix", &pluginpb.Version{Major: proto.Int32(5), Minor: proto.Int32(29), Patch: proto.Int32(0)}, "v5.29.0"},
		{"suffix", &pluginpb.Version{Major: proto.Int32(4), Minor: proto.Int32(25), Patch: proto.Int32(1), Suffix: proto.String("rc1")}, "v4.25.1-rc1"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := formatProtocVersion(tt.v); got != tt.want {
				t.Errorf("formatProtocVersion() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestFormatFileHeader(t *testing.T) {
	got := formatFileHeader("v5.29.0", "api/v1/foo.proto", "foov1", false)
	want := []string{
		"// Code generated by protoc-gen-route. DO NOT EDIT.",
		"// versions:",
		"// - protoc             v5.29.0",
		"// source: api/v1/foo.proto",
		"",
		"package foov1",
		"",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("formatFileHeader() = %#v, want %#v", got, want)
	}

	dep := formatFileHeader("v5.29.0", "api/v1/foo.proto", "foov1", true)
	if dep[3] != "// api/v1/foo.proto is a deprecated file." {
		t.Errorf("deprecated header line = %q", dep[3])
	}
}

func TestFormatMethodComment(t *testing.T) {
	tests := []struct {
		name    string
		method  string
		leading string
		want    string
	}{
		{"empty", "UpdateCount", "", ""},
		{"single line", "UpdateCount", " updates the count\n", "// UpdateCount updates the count"},
		{"multi line", "UpdateCount", "line1\nline2\nline3\n", "// UpdateCount line1\n// line2\n// line3"},
		{"blank interior lines skipped", "UpdateCount", "line1\n\nline2\n", "// UpdateCount line1\n// line2"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := formatMethodComment(tt.method, tt.leading); got != tt.want {
				t.Errorf("formatMethodComment(%q, %q) = %q, want %q", tt.method, tt.leading, got, tt.want)
			}
		})
	}
}

func TestPascalCase(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		{"", ""},
		{"route", "Route"},
		{"callback_query", "CallbackQuery"},
		{"bot-command", "BotCommand"},
		{"multi word key", "MultiWordKey"},
		{"ALLCAPS", "Allcaps"},
		{"__leading", "Leading"},
	}
	for _, tt := range tests {
		t.Run(tt.in, func(t *testing.T) {
			if got := pascalCase(tt.in); got != tt.want {
				t.Errorf("pascalCase(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestImportKeepAlives(t *testing.T) {
	ident := func(path, name string) protogen.GoIdent {
		return protogen.GoIdent{GoName: name, GoImportPath: protogen.GoImportPath(path)}
	}

	t.Run("dedup by import path", func(t *testing.T) {
		// All four idents share one import path, so only the first survives.
		conf := DefaultConfig()
		newRefs, exprRefs := importKeepAlives(conf)
		if len(newRefs) != 1 {
			t.Fatalf("newRefs = %v, want exactly 1", newRefs)
		}
		if newRefs[0] != conf.RequestType {
			t.Errorf("newRefs[0] = %v, want RequestType %v", newRefs[0], conf.RequestType)
		}
		if len(exprRefs) != 0 {
			t.Errorf("exprRefs = %v, want empty (constructor shares the type import path)", exprRefs)
		}
	})

	t.Run("distinct import paths", func(t *testing.T) {
		conf := &Config{
			RequestType:      ident("example.com/req", "Req"),
			ResponseType:     ident("example.com/resp", "Resp"),
			ExtraType:        ident("example.com/extra", "Extra"),
			ExtraConstructor: ident("example.com/ctor", "NewExtra"),
		}
		newRefs, exprRefs := importKeepAlives(conf)
		if len(newRefs) != 3 {
			t.Errorf("newRefs = %v, want 3", newRefs)
		}
		if len(exprRefs) != 1 || exprRefs[0] != conf.ExtraConstructor {
			t.Errorf("exprRefs = %v, want [NewExtra]", exprRefs)
		}
	})

	t.Run("empty idents skipped", func(t *testing.T) {
		// No extra type/constructor: nothing for the extra slots, no var _ = new().
		conf := &Config{
			RequestType:  ident("example.com/req", "Req"),
			ResponseType: ident("example.com/resp", "Resp"),
		}
		newRefs, exprRefs := importKeepAlives(conf)
		if len(newRefs) != 2 {
			t.Errorf("newRefs = %v, want 2", newRefs)
		}
		if len(exprRefs) != 0 {
			t.Errorf("exprRefs = %v, want empty", exprRefs)
		}
	})
}
