package route

import (
	"fmt"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

// formatProtocVersion formats a protoc compiler version as "vMAJOR.MINOR.PATCH[-SUFFIX]".
// A nil version renders as "(unknown)".
func formatProtocVersion(v *pluginpb.Version) string {
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

// formatFileHeader builds the standard "Code generated ... DO NOT EDIT" header
// lines, including the package declaration. When deprecated is true the source
// line is replaced with a deprecation notice.
func formatFileHeader(version, sourcePath, pkgName string, deprecated bool) []string {
	lines := []string{
		"// Code generated by protoc-gen-route. DO NOT EDIT.",
		"// versions:",
		fmt.Sprintf("// - protoc             %s", version),
	}
	if deprecated {
		lines = append(lines, fmt.Sprintf("// %s is a deprecated file.", sourcePath))
	} else {
		lines = append(lines, fmt.Sprintf("// source: %s", sourcePath))
	}
	lines = append(lines, "", fmt.Sprintf("package %s", pkgName), "")
	return lines
}

// formatMethodComment formats a method's leading proto comment into Go doc
// comment lines, prefixing the first line with the method name. Empty input
// yields an empty string.
func formatMethodComment(methodName, leading string) string {
	if leading == "" {
		return ""
	}
	cmp := strings.Split(strings.TrimSuffix(leading, "\n"), "\n")
	if len(cmp) == 0 {
		return ""
	}
	lines := []string{fmt.Sprintf("// %s %s", methodName, strings.TrimSpace(cmp[0]))}
	for _, line := range cmp[1:] {
		if strings.TrimSpace(line) == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("// %s", strings.TrimSpace(line)))
	}
	return strings.Join(lines, "\n")
}

// pascalCase converts a space/underscore/dash separated string into PascalCase.
// It is used to turn the options key (e.g. "callback_query") into a Go-friendly
// identifier fragment (e.g. "CallbackQuery").
func pascalCase(s string) string {
	words := strings.FieldsFunc(s, func(r rune) bool {
		return r == ' ' || r == '_' || r == '-'
	})
	var result strings.Builder
	for _, word := range words {
		if word == "" {
			continue
		}
		word = strings.ToLower(word)
		result.WriteString(string(unicode.ToUpper(rune(word[0]))) + word[1:])
	}
	return result.String()
}

// importKeepAlives returns the config idents that must be referenced via
// `var _ = ...` declarations to keep their imports alive in the generated file.
// newRefs are emitted as `var _ = new(ident)` and exprRefs as `var _ = ident`.
// Idents with an empty name or import path are skipped, and each import path is
// referenced at most once (deduplicated across both groups).
func importKeepAlives(conf *Config) (newRefs []protogen.GoIdent, exprRefs []protogen.GoIdent) {
	seen := make(map[protogen.GoImportPath]bool)
	add := func(dst *[]protogen.GoIdent, id protogen.GoIdent) {
		if id.GoName == "" || id.GoImportPath == "" {
			return
		}
		if seen[id.GoImportPath] {
			return
		}
		seen[id.GoImportPath] = true
		*dst = append(*dst, id)
	}
	add(&newRefs, conf.RequestType)
	add(&newRefs, conf.ResponseType)
	add(&newRefs, conf.ExtraType)
	add(&exprRefs, conf.ExtraConstructor)
	return newRefs, exprRefs
}
