// Code generated by protoc-gen-route. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: basic.proto

package basicv1

import (
	context "context"
	telegram "github.com/go-sphere/sphere/social/telegram"
)

var _ = new(context.Context)
var _ = new(telegram.Update)

const OperationRouteMenuServiceGetMenu = "/testdata.basic.v1.MenuService/GetMenu"
const OperationRouteMenuServiceUpdateCount = "/testdata.basic.v1.MenuService/UpdateCount"

var ExtraRouteDataMenuServiceUpdateCount = telegram.NewMethodExtraData(map[string]string{
	"callback_query": "start",
	"command":        "start",
})

func GetExtraRouteDataByMenuServiceOperation(operation string) *telegram.MethodExtraData {
	switch operation {
	case OperationRouteMenuServiceUpdateCount:
		return ExtraRouteDataMenuServiceUpdateCount
	default:
		return nil
	}
}

func GetAllRouteMenuServiceOperations() []string {
	return []string{
		OperationRouteMenuServiceGetMenu,
		OperationRouteMenuServiceUpdateCount,
	}
}

type MenuServiceRouteServer interface {
	// GetMenu GetMenu returns the menu and carries a route rule without extra data.
	GetMenu(context.Context, *GetMenuRequest) (*GetMenuResponse, error)
	// UpdateCount UpdateCount updates the menu counter.
	// It is triggered by the start command.
	UpdateCount(context.Context, *UpdateCountRequest) (*UpdateCountResponse, error)
}

type MenuServiceRouteCodec interface {
	DecodeGetMenuRequest(ctx context.Context, request *telegram.Update) (*GetMenuRequest, error)
	EncodeGetMenuResponse(ctx context.Context, response *GetMenuResponse) (*telegram.Message, error)
	DecodeUpdateCountRequest(ctx context.Context, request *telegram.Update) (*UpdateCountRequest, error)
	EncodeUpdateCountResponse(ctx context.Context, response *UpdateCountResponse) (*telegram.Message, error)
}

func _MenuService_UpdateCount0_Route_Handler(srv MenuServiceRouteServer, codec MenuServiceRouteCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) func(ctx context.Context, request *telegram.Update) error {
	return func(ctx context.Context, request *telegram.Update) error {
		req, err := codec.DecodeUpdateCountRequest(ctx, request)
		if err != nil {
			return err
		}
		resp, err := srv.UpdateCount(ctx, req)
		if err != nil {
			return err
		}
		msg, err := codec.EncodeUpdateCountResponse(ctx, resp)
		if err != nil {
			return err
		}
		return render(ctx, request, msg)
	}
}

func _MenuService_GetMenu0_Route_Handler(srv MenuServiceRouteServer, codec MenuServiceRouteCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) func(ctx context.Context, request *telegram.Update) error {
	return func(ctx context.Context, request *telegram.Update) error {
		req, err := codec.DecodeGetMenuRequest(ctx, request)
		if err != nil {
			return err
		}
		resp, err := srv.GetMenu(ctx, req)
		if err != nil {
			return err
		}
		msg, err := codec.EncodeGetMenuResponse(ctx, resp)
		if err != nil {
			return err
		}
		return render(ctx, request, msg)
	}
}

func RegisterMenuServiceRouteServer(srv MenuServiceRouteServer, codec MenuServiceRouteCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) map[string]func(ctx context.Context, request *telegram.Update) error {
	handlers := make(map[string]func(ctx context.Context, request *telegram.Update) error)
	handlers[OperationRouteMenuServiceUpdateCount] = _MenuService_UpdateCount0_Route_Handler(srv, codec, render)
	handlers[OperationRouteMenuServiceGetMenu] = _MenuService_GetMenu0_Route_Handler(srv, codec, render)
	return handlers
}
