// Code generated by protoc-gen-route. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: complex.proto

package complexv1

import (
	context "context"
	telegram "github.com/go-sphere/sphere/social/telegram"
)

var _ = new(context.Context)
var _ = new(telegram.Update)

const OperationRouteOrderServiceCreate = "/testdata.complex.v1.OrderService/Create"

func GetExtraRouteDataByOrderServiceOperation(operation string) *telegram.MethodExtraData {
	switch operation {
	default:
		return nil
	}
}

func GetAllRouteOrderServiceOperations() []string {
	return []string{
		OperationRouteOrderServiceCreate,
	}
}

type OrderServiceRouteServer interface {
	// Create Create is a unary method with a route rule.
	Create(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
}

type OrderServiceRouteCodec interface {
	DecodeCreateRequest(ctx context.Context, request *telegram.Update) (*CreateOrderRequest, error)
	EncodeCreateResponse(ctx context.Context, response *CreateOrderResponse) (*telegram.Message, error)
}

func _OrderService_Create0_Route_Handler(srv OrderServiceRouteServer, codec OrderServiceRouteCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) func(ctx context.Context, request *telegram.Update) error {
	return func(ctx context.Context, request *telegram.Update) error {
		req, err := codec.DecodeCreateRequest(ctx, request)
		if err != nil {
			return err
		}
		resp, err := srv.Create(ctx, req)
		if err != nil {
			return err
		}
		msg, err := codec.EncodeCreateResponse(ctx, resp)
		if err != nil {
			return err
		}
		return render(ctx, request, msg)
	}
}

func RegisterOrderServiceRouteServer(srv OrderServiceRouteServer, codec OrderServiceRouteCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) map[string]func(ctx context.Context, request *telegram.Update) error {
	handlers := make(map[string]func(ctx context.Context, request *telegram.Update) error)
	handlers[OperationRouteOrderServiceCreate] = _OrderService_Create0_Route_Handler(srv, codec, render)
	return handlers
}

const OperationRouteUserServiceCreate = "/testdata.complex.v1.UserService/Create"

var ExtraRouteDataUserServiceCreate = telegram.NewMethodExtraData(map[string]string{
	"scope": "user",
})

func GetExtraRouteDataByUserServiceOperation(operation string) *telegram.MethodExtraData {
	switch operation {
	case OperationRouteUserServiceCreate:
		return ExtraRouteDataUserServiceCreate
	default:
		return nil
	}
}

func GetAllRouteUserServiceOperations() []string {
	return []string{
		OperationRouteUserServiceCreate,
	}
}

type UserServiceRouteServer interface {
	// Create Create is a second method with the same GoName as OrderService.Create.
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

type UserServiceRouteCodec interface {
	DecodeCreateRequest(ctx context.Context, request *telegram.Update) (*CreateUserRequest, error)
	EncodeCreateResponse(ctx context.Context, response *CreateUserResponse) (*telegram.Message, error)
}

func _UserService_Create1_Route_Handler(srv UserServiceRouteServer, codec UserServiceRouteCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) func(ctx context.Context, request *telegram.Update) error {
	return func(ctx context.Context, request *telegram.Update) error {
		req, err := codec.DecodeCreateRequest(ctx, request)
		if err != nil {
			return err
		}
		resp, err := srv.Create(ctx, req)
		if err != nil {
			return err
		}
		msg, err := codec.EncodeCreateResponse(ctx, resp)
		if err != nil {
			return err
		}
		return render(ctx, request, msg)
	}
}

func RegisterUserServiceRouteServer(srv UserServiceRouteServer, codec UserServiceRouteCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) map[string]func(ctx context.Context, request *telegram.Update) error {
	handlers := make(map[string]func(ctx context.Context, request *telegram.Update) error)
	handlers[OperationRouteUserServiceCreate] = _UserService_Create1_Route_Handler(srv, codec, render)
	return handlers
}
