// Code generated by protoc-gen-route. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: complex.proto

package complexv1

import (
	context "context"
	telegram "github.com/go-sphere/sphere/social/telegram"
)

var _ = new(context.Context)
var _ = new(telegram.Update)

const OperationBotUserServiceDelete = "/testdata.complex.v1.UserService/Delete"

func GetExtraBotDataByUserServiceOperation(operation string) *telegram.MethodExtraData {
	switch operation {
	default:
		return nil
	}
}

func GetAllBotUserServiceOperations() []string {
	return []string{
		OperationBotUserServiceDelete,
	}
}

type UserServiceBotServer interface {
	// Delete Delete only carries a rule under the "bot" key; it is skipped when
	// generating the default "route" key but generated for a "bot" run.
	Delete(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

type UserServiceBotCodec interface {
	DecodeDeleteRequest(ctx context.Context, request *telegram.Update) (*DeleteUserRequest, error)
	EncodeDeleteResponse(ctx context.Context, response *DeleteUserResponse) (*telegram.Message, error)
}

func _UserService_Delete0_Bot_Handler(srv UserServiceBotServer, codec UserServiceBotCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) func(ctx context.Context, request *telegram.Update) error {
	return func(ctx context.Context, request *telegram.Update) error {
		req, err := codec.DecodeDeleteRequest(ctx, request)
		if err != nil {
			return err
		}
		resp, err := srv.Delete(ctx, req)
		if err != nil {
			return err
		}
		msg, err := codec.EncodeDeleteResponse(ctx, resp)
		if err != nil {
			return err
		}
		return render(ctx, request, msg)
	}
}

func RegisterUserServiceBotServer(srv UserServiceBotServer, codec UserServiceBotCodec, render func(ctx context.Context, request *telegram.Update, msg *telegram.Message) error) map[string]func(ctx context.Context, request *telegram.Update) error {
	handlers := make(map[string]func(ctx context.Context, request *telegram.Update) error)
	handlers[OperationBotUserServiceDelete] = _UserService_Delete0_Bot_Handler(srv, codec, render)
	return handlers
}
